name: SMP
version: 1.0
author: Daniel Zhuo
main: com.sirdanieliii.SMP
api-version: 1.15
commands:
  wand:
    description: Spawns a mysterious wand - OP Needed
    usage: /wand
  ivan:
    description: Spawns an Ivan (Donkey or Dog) - OP Needed
    usage: /ivan <type>
  coords:
    description: Saves coords so you won't get lost
    usage: /coords <action> <type>
  death:
    description: Statistics about your deaths and murders :D
    usage: /death <stat>
