name: SMP
version: 1.05.1
author: Sir Daniel III
main: com.sirdanieliii.SMP
api-version: 1.17
commands:
  coords:
    description: Saves coords so you won't get lost
    usage: /coords <action> <type>
  death:
    description: Statistics about your deaths and murders :D
    usage: /death <stat>
  ivan:
    description: <OP Required> Spawns an Ivan (Donkey or Dog)
    usage: /ivan <type>
  wand:
    description: <OP Required> Spawns a weapon of the Gods...
    usage: /wand